#!/usr/bin/env bash
set -Eeuo pipefail

fatal() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
ok() { printf 'PASS: %s\n' "$1"; }

systemctl is-active --quiet postgresql.service || fatal "PostgreSQL is not active"
ok "PostgreSQL service is active"

systemctl is-active --quiet redis-server.service || fatal "Redis is not active"
ok "Redis service is active"

systemctl is-active --quiet honcho-api.service || fatal "Honcho API service is not active"
ok "Honcho API service is active"

systemctl is-active --quiet honcho-deriver.service || fatal "Honcho Deriver service is not active"
ok "Honcho Deriver service is active"

ss -ltnH 'sport = :8000' | grep -q . || fatal "Nothing is listening on TCP port 8000"
ok "Honcho API is listening on TCP port 8000"

health="$(curl -fsS --max-time 5 http://127.0.0.1:8000/health)" || fatal "Honcho /health request failed"
printf '%s' "$health" | grep -Eq '"status"[[:space:]]*:[[:space:]]*"ok"' || fatal "Honcho /health did not report status ok"
ok "Honcho /health reports ok"

redis-cli ping | grep -qx PONG || fatal "Redis PING failed"
ok "Redis PING succeeded"

vector_version="$(runuser -u postgres -- psql -Atq -d honcho -c "SELECT extversion FROM pg_extension WHERE extname='vector';")"
[[ -n "$vector_version" ]] || fatal "pgvector extension is missing from the honcho database"
ok "pgvector extension is installed (${vector_version})"

set -a
# /etc/honcho/environment is generated by the installer with single-quoted,
# single-line values so it is safe to source for this local diagnostic.
# shellcheck source=/dev/null
source /etc/honcho/environment
set +a
(
  cd /opt/honcho/current
  runuser -u honcho --preserve-environment -- env HOME=/var/lib/honcho \
    /opt/honcho/current/.venv/bin/python - <<'PY' >/dev/null
import asyncio
from sqlalchemy import text
from src.db import engine

async def main():
    async with engine.connect() as conn:
        value = await conn.scalar(text("SELECT 1"))
        if value != 1:
            raise SystemExit(1)
    await engine.dispose()

asyncio.run(main())
PY
) || fatal "Application database connection failed"
ok "Honcho application database connection succeeded"

[[ -L /opt/honcho/current ]] || fatal "/opt/honcho/current is not a release symlink"
[[ -f /etc/honcho/installation.json ]] || fatal "Installation manifest is missing"
ok "Release symlink and installation manifest are present"

if command -v docker >/dev/null 2>&1 || command -v podman >/dev/null 2>&1; then
  fatal "A nested Docker/Podman runtime is present; this adaptation does not require one"
fi
ok "No nested Docker/Podman runtime is installed"

printf '\nHoncho native LXC health check passed.\n'
